version: "2"
run:
  concurrency: 4
  tests: true
linters:
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - godot
    - gomoddirectives
    - gosec
    - ireturn
    - nlreturn
    - nolintlint
    - paralleltest
    - perfsprint
    - testpackage
    - varnamelen
    - wrapcheck
  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
    funlen:
      lines: 210
      statements: 50
    lll:
      line-length: 200
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
