# Copyright Contributors to the Open Cluster Management project
# Licensed under the Apache License 2.0

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.21 AS builder

WORKDIR /workspace

COPY . .

RUN  make thanos-receive-controller

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

COPY --from=builder /workspace/thanos-receive-controller /usr/bin/thanos-receive-controller

RUN microdnf update -y && microdnf clean all

USER 65534

ENTRYPOINT ["/usr/bin/thanos-receive-controller"]
